backend:
  name: test-repo
  branch: master

media_folder: static/assets
public_folder: assets

collections:
  - name: "pages"
    label: "Pages"
    create: true
    files:
      - file: "src/markdown/aboutUs/index.md"
        label: "About Us"
        name: "aboutUs"
        fields:
          - { name: path, label: Path }
          - { name: title, label: Title }
